version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install

  build:
    commands:
      - echo Building the project and running tests...
      - mvn clean package

  post_build:
    commands:
      - echo Build and test completed successfully.

artifacts:
  files:
    - target/*.jar
